### ISSUE TITLE
Create new material for Product guide

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-node#401]
The code for this task won't be in this repo, it will be in this one:
https://github.com/stormpath/stormpath-documentation

#### Todo

- [x] Quickstart
- [x] Account Management (see https://github.com/stormpath/stormpath-documentation/issues/79)
- [x] Authentication (https://github.com/stormpath/stormpath-documentation/pull/233)
- [x] Authorization (https://github.com/stormpath/stormpath-documentation/pull/232)
- [x] ID site (https://github.com/stormpath/stormpath-documentation/pull/231)
- [ ] Multi-tenancy

**Comment by typerandom** [comment]
@robertjd I have added Node.js to the quickstart. But is the thought to add code examples to e.g: https://github.com/stormpath/stormpath-documentation/blob/master/source/accnt_mgmt.rst#how-to-make-a-cloud-directory? From what I can see, there's only code examples in the quickstart so far.

**Comment by typerandom** [comment]
From Hipchat:

>**Robin Orheden·12:42 PM**
-@Jakub Quick question. I've fixed the quickstart. What else do I need to add Node.js -code examples to? From what I can see there's only code examples in the quickstart.

>**Jakub Swiatczak·12:42 PM**
-that's it for now
-wanted everyone to try it and make sure it works and we have buy in before we start on the rest of the doc
-figured the QuickStart was a good proof of concept

**Comment by typerandom** [comment]
@robertjd Should we just close this until we have more work to do? Or keep it open?

**Comment by robertjd** [comment]
Requirements are now updated here: https://github.com/stormpath/stormpath-documentation/issues/79

I'm going to remove the on-hold label.

**Comment by robertjd** [comment]
More todos for us on this front: https://github.com/stormpath/stormpath-documentation/issues/79#issuecomment-202492448

**Comment by robertjd** [comment]
We can find the remaining work by searching for "node.todo" in the documentation repoistory.  However, most of the remaining work will require us to link to our API documentation for the Node SDK, which we are about to replace with JsDoc.  As such, I considered this issue blocked on that that, #149 .  I will bring this back into open until we can revisit.

Also: for some use cases, I'd like to try showing express-stormpath examples, as most developers are working with that library.
